/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Global Data Header File                                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : KPP_Global.h                              */
/* Equation file        : KPP.kpp                                   */
/* Output root filename : KPP                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include "omp.h"
#include "KPP/KPP_Parameters.h"

#ifndef KPP_GLOBAL_H_INCLUDED
#define KPP_GLOBAL_H_INCLUDED

/* Declaration of global variables                                  */

extern double C[NSPEC];                         /* Concentration of all species */
extern double * VAR;
extern double * FIX;
extern double RCONST[NREACT];                   /* Rate constants (global) */
extern double TIME;                             /* Current integration time */
extern int LOOKAT[NLOOKAT];                     /* Indexes of species to look at */
extern const char * SPC_NAMES[NSPEC];           /* Names of chemical species */
extern char * SMASS[NMASS];                     /* Names of atoms for mass balance */
extern const char * EQN_NAMES[NREACT];          /* Equation names */
extern char * EQN_TAGS[NREACT];                 /* Equation tags */

/* INLINED global variable declarations                             */

extern double NOON_JRATES[NPHOTOL];             /* Noon-time photolysis rates */
extern double PHOTOL[NPHOTOL];                  /* Photolysis rates */
extern double HET[NSPEC][3];                    /* Heterogeneous reaction rates */
extern double SZA_CST[3];                       /* Constants to compute cosSZA */

/* The following variables need to be declared THREADPRIVATE
 * because they get written to within an OpenMP parallel loop */
#pragma omp threadprivate( C, VAR, FIX, RCONST, NOON_JRATES, PHOTOL, HET, TIME, SZA_CST )

/* INLINED global variable declarations                             */

#endif /* KPP_GLOBAL_H_INCLUDED */
