/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Auxiliary Routines File                                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : KPP_Util.c                                */
/* Time                 : Tue Sep  4 17:12:00 2018                  */
/* Working directory    : /home/fritzt/Documents/kpp-2.2.3/Research/UCX_Forw_C_2 */
/* Equation file        : KPP.kpp                                   */
/* Output root filename : KPP                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "KPP_Parameters.h"
#include "KPP_Global.h"
#include "KPP_Sparse.h"


/* User INLINED Utility Functions                                   */

/* End INLINED Utility Functions                                    */

/* Utility Functions from KPP_HOME/util/util                        */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* UTIL - Utility functions                                         */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/*
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
*/
double min( double x, double y )
{
  return ( x <= y ) ? x : y;
}

double max( double x, double y )
{
  return ( x >= y ) ? x : y;
}

static FILE *fpDat = 0;

int InitSaveData()
{
  fpDat = fopen("KPP.dat", "w");
  if( fpDat == 0 ) {
    printf("\n Can't create file : KPP.dat");
    exit(1);
  }
  return 0;
}

int SaveData()
{
int i;

  fprintf( fpDat, "%6.1f ", TIME/3600.0 );
  for( i = 0; i < NLOOKAT; i++ )
    fprintf( fpDat, "%24.16e ", C[ LOOKAT[i] ]/CFACTOR );
  fprintf( fpDat, "\n");
  return 0;
}

int CloseSaveData()
{
  fclose( fpDat );
  return 0;
}

int GenerateMatlab( char * prefix )
{
int i;
FILE *fpMatlab;
  
  fpMatlab = fopen("KPP.m", "w");
  if( fpMatlab == 0 ) {
    printf("\n Can't create file : KPP.m");
    exit(1);
  }

  fprintf(fpMatlab, "load KPP.dat;\n");
  fprintf(fpMatlab, "%sc = KPP;\n", prefix);
  fprintf(fpMatlab, "clear KPP;\n");
  fprintf(fpMatlab, "%st=%sc(:,1);\n", prefix, prefix);
  fprintf(fpMatlab, "%sc(:,1)=[];\n", prefix);
  
  for( i = 0; i < NLOOKAT; i++ )
    fprintf( fpMatlab, "%s%s = %sc(:,%d);\n", 
            prefix, SPC_NAMES[LOOKAT[i]], 
            prefix, i+1 );
  
  fclose( fpMatlab );
  return 0;
}

/* End Utility Functions from KPP_HOME/util/util                    */
/* End of UTIL function                                             */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Shuffle_user2kpp - function to copy concentrations from USER to KPP */
/*   Arguments :                                                    */
/*      V_USER    - Concentration of variable species in USER's order */
/*      V         - Concentrations of variable species (local)      */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Shuffle_user2kpp( 
  double V_USER[],                       /* Concentration of variable species in USER's order */
  double V[]                             /* Concentrations of variable species (local) */
)
{
  V[60] = V_USER[0];
  V[67] = V_USER[1];
  V[109] = V_USER[2];
  V[8] = V_USER[3];
  V[89] = V_USER[4];
  V[66] = V_USER[5];
  V[33] = V_USER[6];
  V[14] = V_USER[7];
  V[111] = V_USER[8];
  V[64] = V_USER[9];
  V[125] = V_USER[10];
  V[80] = V_USER[11];
  V[12] = V_USER[12];
  V[84] = V_USER[13];
  V[62] = V_USER[14];
  V[53] = V_USER[15];
  V[112] = V_USER[16];
  V[78] = V_USER[17];
  V[95] = V_USER[18];
  V[13] = V_USER[19];
  V[90] = V_USER[20];
  V[20] = V_USER[21];
  V[120] = V_USER[22];
  V[37] = V_USER[23];
  V[94] = V_USER[24];
  V[52] = V_USER[25];
  V[91] = V_USER[26];
  V[77] = V_USER[27];
  V[51] = V_USER[28];
  V[42] = V_USER[29];
  V[43] = V_USER[30];
  V[19] = V_USER[31];
  V[81] = V_USER[32];
  V[106] = V_USER[33];
  V[76] = V_USER[34];
  V[92] = V_USER[35];
  V[21] = V_USER[36];
  V[63] = V_USER[37];
  V[9] = V_USER[38];
  V[110] = V_USER[39];
  V[104] = V_USER[40];
  V[97] = V_USER[41];
  V[126] = V_USER[42];
  V[22] = V_USER[43];
  V[93] = V_USER[44];
  V[40] = V_USER[45];
  V[108] = V_USER[46];
  V[6] = V_USER[47];
  V[5] = V_USER[48];
  V[41] = V_USER[49];
  V[114] = V_USER[50];
  V[121] = V_USER[51];
  V[115] = V_USER[52];
  V[117] = V_USER[53];
  V[118] = V_USER[54];
  V[119] = V_USER[55];
  V[122] = V_USER[56];
  V[7] = V_USER[57];
  V[50] = V_USER[58];
  V[74] = V_USER[59];
  V[26] = V_USER[60];
  V[1] = V_USER[61];
  V[79] = V_USER[62];
  V[55] = V_USER[63];
  V[27] = V_USER[64];
  V[87] = V_USER[65];
  V[101] = V_USER[66];
  V[100] = V_USER[67];
  V[32] = V_USER[68];
  V[15] = V_USER[69];
  V[16] = V_USER[70];
  V[103] = V_USER[71];
  V[82] = V_USER[72];
  V[86] = V_USER[73];
  V[34] = V_USER[74];
  V[47] = V_USER[75];
  V[24] = V_USER[76];
  V[71] = V_USER[77];
  V[35] = V_USER[78];
  V[107] = V_USER[79];
  V[28] = V_USER[80];
  V[29] = V_USER[81];
  V[113] = V_USER[82];
  V[102] = V_USER[83];
  V[59] = V_USER[84];
  V[123] = V_USER[85];
  V[2] = V_USER[86];
  V[54] = V_USER[87];
  V[10] = V_USER[88];
  V[58] = V_USER[89];
  V[44] = V_USER[90];
  V[96] = V_USER[91];
  V[49] = V_USER[92];
  V[83] = V_USER[93];
  V[38] = V_USER[94];
  V[39] = V_USER[95];
  V[48] = V_USER[96];
  V[98] = V_USER[97];
  V[99] = V_USER[98];
  V[61] = V_USER[99];
  V[30] = V_USER[100];
  V[68] = V_USER[101];
  V[31] = V_USER[102];
  V[3] = V_USER[103];
  V[45] = V_USER[104];
  V[36] = V_USER[105];
  V[4] = V_USER[106];
  V[46] = V_USER[107];
  V[69] = V_USER[108];
  V[73] = V_USER[109];
  V[56] = V_USER[110];
  V[65] = V_USER[111];
  V[70] = V_USER[112];
  V[72] = V_USER[113];
  V[75] = V_USER[114];
  V[25] = V_USER[115];
  V[116] = V_USER[116];
  V[57] = V_USER[117];
  V[105] = V_USER[118];
  V[23] = V_USER[119];
  V[17] = V_USER[120];
  V[11] = V_USER[121];
  V[18] = V_USER[122];
  V[85] = V_USER[123];
  V[124] = V_USER[124];
  V[88] = V_USER[125];
}

/* End of Shuffle_user2kpp function                                 */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Shuffle_kpp2user - function to restore concentrations from KPP to USER */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      V_USER    - Concentration of variable species in USER's order */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Shuffle_kpp2user( 
  double V[],                            /* Concentrations of variable species (local) */
  double V_USER[]                        /* Concentration of variable species in USER's order */
)
{
  V_USER[0] = V[60];
  V_USER[1] = V[67];
  V_USER[2] = V[109];
  V_USER[3] = V[8];
  V_USER[4] = V[89];
  V_USER[5] = V[66];
  V_USER[6] = V[33];
  V_USER[7] = V[14];
  V_USER[8] = V[111];
  V_USER[9] = V[64];
  V_USER[10] = V[125];
  V_USER[11] = V[80];
  V_USER[12] = V[12];
  V_USER[13] = V[84];
  V_USER[14] = V[62];
  V_USER[15] = V[53];
  V_USER[16] = V[112];
  V_USER[17] = V[78];
  V_USER[18] = V[95];
  V_USER[19] = V[13];
  V_USER[20] = V[90];
  V_USER[21] = V[20];
  V_USER[22] = V[120];
  V_USER[23] = V[37];
  V_USER[24] = V[94];
  V_USER[25] = V[52];
  V_USER[26] = V[91];
  V_USER[27] = V[77];
  V_USER[28] = V[51];
  V_USER[29] = V[42];
  V_USER[30] = V[43];
  V_USER[31] = V[19];
  V_USER[32] = V[81];
  V_USER[33] = V[106];
  V_USER[34] = V[76];
  V_USER[35] = V[92];
  V_USER[36] = V[21];
  V_USER[37] = V[63];
  V_USER[38] = V[9];
  V_USER[39] = V[110];
  V_USER[40] = V[104];
  V_USER[41] = V[97];
  V_USER[42] = V[126];
  V_USER[43] = V[22];
  V_USER[44] = V[93];
  V_USER[45] = V[40];
  V_USER[46] = V[108];
  V_USER[47] = V[6];
  V_USER[48] = V[5];
  V_USER[49] = V[41];
  V_USER[50] = V[114];
  V_USER[51] = V[121];
  V_USER[52] = V[115];
  V_USER[53] = V[117];
  V_USER[54] = V[118];
  V_USER[55] = V[119];
  V_USER[56] = V[122];
  V_USER[57] = V[7];
  V_USER[58] = V[50];
  V_USER[59] = V[74];
  V_USER[60] = V[26];
  V_USER[61] = V[1];
  V_USER[62] = V[79];
  V_USER[63] = V[55];
  V_USER[64] = V[27];
  V_USER[65] = V[87];
  V_USER[66] = V[101];
  V_USER[67] = V[100];
  V_USER[68] = V[32];
  V_USER[69] = V[15];
  V_USER[70] = V[16];
  V_USER[71] = V[103];
  V_USER[72] = V[82];
  V_USER[73] = V[86];
  V_USER[74] = V[34];
  V_USER[75] = V[47];
  V_USER[76] = V[24];
  V_USER[77] = V[71];
  V_USER[78] = V[35];
  V_USER[79] = V[107];
  V_USER[80] = V[28];
  V_USER[81] = V[29];
  V_USER[82] = V[113];
  V_USER[83] = V[102];
  V_USER[84] = V[59];
  V_USER[85] = V[123];
  V_USER[86] = V[2];
  V_USER[87] = V[54];
  V_USER[88] = V[10];
  V_USER[89] = V[58];
  V_USER[90] = V[44];
  V_USER[91] = V[96];
  V_USER[92] = V[49];
  V_USER[93] = V[83];
  V_USER[94] = V[38];
  V_USER[95] = V[39];
  V_USER[96] = V[48];
  V_USER[97] = V[98];
  V_USER[98] = V[99];
  V_USER[99] = V[61];
  V_USER[100] = V[30];
  V_USER[101] = V[68];
  V_USER[102] = V[31];
  V_USER[103] = V[3];
  V_USER[104] = V[45];
  V_USER[105] = V[36];
  V_USER[106] = V[4];
  V_USER[107] = V[46];
  V_USER[108] = V[69];
  V_USER[109] = V[73];
  V_USER[110] = V[56];
  V_USER[111] = V[65];
  V_USER[112] = V[70];
  V_USER[113] = V[72];
  V_USER[114] = V[75];
  V_USER[115] = V[25];
  V_USER[116] = V[116];
  V_USER[117] = V[57];
  V_USER[118] = V[105];
  V_USER[119] = V[23];
  V_USER[120] = V[17];
  V_USER[121] = V[11];
  V_USER[122] = V[18];
  V_USER[123] = V[85];
  V_USER[124] = V[124];
  V_USER[125] = V[88];
}

/* End of Shuffle_kpp2user function                                 */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* GetMass - compute total mass of selected atoms                   */
/*   Arguments :                                                    */
/*      CL        - Concentration of all species (local)            */
/*      Mass      - value of mass balance                           */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void GetMass( 
  double CL[],                           /* Concentration of all species (local) */
  double Mass[]                          /* value of mass balance */
)
{
}

/* End of GetMass function                                          */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


