/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialization File                                              */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : KPP_Initialize.c                          */
/* Time                 : Tue Sep  4 17:12:00 2018                  */
/* Working directory    : /home/fritzt/Documents/kpp-2.2.3/Research/UCX_Forw_C_2 */
/* Equation file        : KPP.kpp                                   */
/* Output root filename : KPP                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "KPP_Parameters.h"
#include "KPP_Global.h"
#include "KPP_Sparse.h"
//
//
///* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
///*                                                                  */
///* Initialize - function to initialize concentrations               */
///*   Arguments :                                                    */
///*                                                                  */
///* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
//
void Initialize( 
)
{
    printf("Hello KPP\n");
//int i;                                  
//double x;                               
//
////  CFACTOR = 1.000000e+00;
//
//  x = (0.)*CFACTOR;
//  for( i = 0; i < NVAR; i++ )
//    VAR[i] = x;
//
//  x = (0.)*CFACTOR;
//  for( i = 0; i < NFIX; i++ )
//    FIX[i] = x;
//
//  VAR[0] = (3.600E-04)*CFACTOR;
//  VAR[1] = (1.000E-20)*CFACTOR;
//  VAR[2] = (1.000E-20)*CFACTOR;
//  VAR[3] = (1.000E-20)*CFACTOR;
//  VAR[4] = (1.000E-20)*CFACTOR;
//  VAR[5] = (3.000E-07)*CFACTOR;
//  VAR[6] = (4.000E-25)*CFACTOR;
//  VAR[7] = (1.000E-20)*CFACTOR;
//  VAR[8] = (1.000E-20)*CFACTOR;
//  VAR[9] = (1.000E-20)*CFACTOR;
//  VAR[10] = (1.000E-20)*CFACTOR;
//  VAR[11] = (1.000E-20)*CFACTOR;
//  VAR[12] = (1.000E-20)*CFACTOR;
//  VAR[13] = (4.000E-15)*CFACTOR;
//  VAR[14] = (4.800E-11)*CFACTOR;
//  VAR[15] = (1.000E-20)*CFACTOR;
//  VAR[16] = (1.000E-20)*CFACTOR;
//  VAR[17] = (1.000E-20)*CFACTOR;
//  VAR[18] = (1.000E-20)*CFACTOR;
//  VAR[19] = (2.000E-10)*CFACTOR;
//  VAR[20] = (2.360E-11)*CFACTOR;
//  VAR[21] = (1.000E-20)*CFACTOR;
//  VAR[22] = (1.200E-09)*CFACTOR;
//  VAR[23] = (1.000E-20)*CFACTOR;
//  VAR[24] = (1.000E-20)*CFACTOR;
//  VAR[25] = (3.500E-18)*CFACTOR;
//  VAR[26] = (1.000E-20)*CFACTOR;
//  VAR[27] = (1.000E-20)*CFACTOR;
//  VAR[28] = (1.000E-70)*CFACTOR;
//  VAR[29] = (1.000E-20)*CFACTOR;
//  VAR[30] = (1.000E-20)*CFACTOR;
//  VAR[31] = (1.000E-20)*CFACTOR;
//  VAR[32] = (1.000E-20)*CFACTOR;
//  VAR[33] = (2.590E-12)*CFACTOR;
//  VAR[34] = (1.000E-20)*CFACTOR;
//  VAR[35] = (1.000E-20)*CFACTOR;
//  VAR[36] = (1.000E-20)*CFACTOR;
//  VAR[37] = (1.000E-20)*CFACTOR;
//  VAR[38] = (1.000E-20)*CFACTOR;
//  VAR[39] = (1.000E-20)*CFACTOR;
//  VAR[40] = (1.000E-20)*CFACTOR;
//  VAR[41] = (1.200E-11)*CFACTOR;
//  VAR[42] = (1.000E-20)*CFACTOR;
//  VAR[43] = (1.000E-20)*CFACTOR;
//  VAR[44] = (1.000E-20)*CFACTOR;
//  VAR[45] = (1.000E-20)*CFACTOR;
//  VAR[46] = (1.000E-20)*CFACTOR;
//  VAR[47] = (1.000E-20)*CFACTOR;
//  VAR[48] = (1.000E-20)*CFACTOR;
//  VAR[49] = (1.000E-20)*CFACTOR;
//  VAR[50] = (1.000E-20)*CFACTOR;
//  VAR[51] = (1.000E-20)*CFACTOR;
//  VAR[52] = (1.000E-20)*CFACTOR;
//  VAR[53] = (4.000E-20)*CFACTOR;
//  VAR[54] = (1.700E-13)*CFACTOR;
//  VAR[55] = (6.000E-12)*CFACTOR;
//  VAR[56] = (1.000E-20)*CFACTOR;
//  VAR[57] = (1.000E-20)*CFACTOR;
//  VAR[58] = (1.000E-20)*CFACTOR;
//  VAR[59] = (6.600E-14)*CFACTOR;
//  VAR[60] = (1.000E-20)*CFACTOR;
//  VAR[61] = (1.000E-20)*CFACTOR;
//  VAR[62] = (1.000E-20)*CFACTOR;
//  VAR[63] = (1.000E-20)*CFACTOR;
//  VAR[64] = (1.700E-06)*CFACTOR;
//  VAR[65] = (1.000E-20)*CFACTOR;
//  VAR[66] = (1.000E-20)*CFACTOR;
//  VAR[67] = (7.500E-10)*CFACTOR;
//  VAR[68] = (1.000E-20)*CFACTOR;
//  VAR[69] = (1.000E-20)*CFACTOR;
//  VAR[70] = (1.000E-20)*CFACTOR;
//  VAR[71] = (1.000E-20)*CFACTOR;
//  VAR[72] = (1.000E-20)*CFACTOR;
//  VAR[73] = (1.000E-20)*CFACTOR;
//  VAR[74] = (1.000E-20)*CFACTOR;
//  VAR[75] = (1.000E-20)*CFACTOR;
//  VAR[76] = (1.000E-20)*CFACTOR;
//  VAR[77] = (1.000E-20)*CFACTOR;
//  VAR[78] = (2.720E-12)*CFACTOR;
//  VAR[79] = (1.000E-20)*CFACTOR;
//  VAR[80] = (1.000E-20)*CFACTOR;
//  VAR[81] = (1.000E-20)*CFACTOR;
//  VAR[82] = (1.000E-20)*CFACTOR;
//  VAR[83] = (1.000E-20)*CFACTOR;
//  VAR[84] = (1.000E-20)*CFACTOR;
//  VAR[85] = (1.300E-12)*CFACTOR;
//  VAR[86] = (1.000E-20)*CFACTOR;
//  VAR[87] = (1.000E-20)*CFACTOR;
//  VAR[88] = (1.700E-13)*CFACTOR;
//  VAR[89] = (1.000E-20)*CFACTOR;
//  VAR[90] = (2.170E-10)*CFACTOR;
//  VAR[91] = (1.000E-20)*CFACTOR;
//  VAR[92] = (1.000E-20)*CFACTOR;
//  VAR[93] = (1.000E-20)*CFACTOR;
//  VAR[94] = (1.000E-20)*CFACTOR;
//  VAR[95] = (1.000E-20)*CFACTOR;
//  VAR[96] = (1.000E-20)*CFACTOR;
//  VAR[97] = (1.000E-20)*CFACTOR;
//  VAR[98] = (1.000E-20)*CFACTOR;
//  VAR[99] = (1.000E-20)*CFACTOR;
//  VAR[100] = (1.000E-20)*CFACTOR;
//  VAR[101] = (1.000E-20)*CFACTOR;
//  VAR[102] = (1.300E-14)*CFACTOR;
//  VAR[103] = (1.000E-20)*CFACTOR;
//  VAR[104] = (1.000E-20)*CFACTOR;
//  VAR[105] = (1.000E-14)*CFACTOR;
//  VAR[106] = (1.000E-20)*CFACTOR;
//  VAR[107] = (1.250E-10)*CFACTOR;
//  VAR[108] = (1.000E-20)*CFACTOR;
//  VAR[109] = (1.600E-10)*CFACTOR;
//  VAR[110] = (1.000E-20)*CFACTOR;
//  VAR[111] = (1.020E-11)*CFACTOR;
//  VAR[112] = (3.84E-05)*CFACTOR;
//  VAR[113] = (9.100E-16)*CFACTOR;
//  VAR[114] = (4.410E-11)*CFACTOR;
//  VAR[115] = (1.300E-11)*CFACTOR;
//  VAR[116] = (1.600E-17)*CFACTOR;
//  VAR[117] = (1.300E-16)*CFACTOR;
//  VAR[118] = (1.000E-20)*CFACTOR;
//  VAR[119] = (6.460E-08)*CFACTOR;
//  VAR[120] = (1.020E-12)*CFACTOR;
//  VAR[121] = (5.880E-11)*CFACTOR;
//  VAR[122] = (7.000E-14)*CFACTOR;
//  VAR[123] = (3.700E-14)*CFACTOR;
//  VAR[124] = (3.160E-12)*CFACTOR;
//  VAR[125] = (5.510E-08)*CFACTOR;
//  VAR[126] = (5.400E-12)*CFACTOR;
//  FIX[0] = (3.000E-09)*CFACTOR;
//  FIX[1] = (1.000E-20)*CFACTOR;
//  FIX[2] = (2.700E-07)*CFACTOR;
//  FIX[3] = (1.800E-09)*CFACTOR;
//  FIX[4] = (1.000E-20)*CFACTOR;
//  FIX[5] = (7.808E-01)*CFACTOR;
//  FIX[6] = (2.095E-01)*CFACTOR;
//  FIX[7] = (1.000E-20)*CFACTOR;
///* constant rate coefficients                                       */
///* END constant rate coefficients                                   */
//
///* INLINED initializations                                          */
//
///* End INLINED initializations                                      */
//
}
//
///* End of Initialize function                                       */
///* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


