name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Fetch docker image with specific gcc version prebuilt
    container: gcc:${{ matrix.gcc }}

    strategy:
      matrix:
        gcc: [11.2, 14.3]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake curl zip unzip tar

      - name: Cache vcpkg binary cache
        uses: actions/cache@v5
        with:
          path: vcpkg-binary-cache
          key: vcpkg-bincache-${{ runner.os }}-gcc${{ matrix.gcc }}-${{ hashFiles('Code.v05-00/vcpkg.json') }}

      # For some reason we need to specify the working directory AND create the vcpkg-binary-cache/ directory
      # in this step otherwise vcpkg will fail during CMake configure when there are no cached files on the
      # GitHub Actions Cache (if there are cached files, it works...).
      # The error being that the VCPKG_DEFAULT_BINARY_CACHE variable is not a directory.
      # This is unclear to me why it does not work, and might be related to Docker things... 
      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        env:
          VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-binary-cache
        run: |
          mkdir -p vcpkg-binary-cache
          cmake -B build -S Code.v05-00 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure